Consensus parts in javascript
Zigurat-blockchain-masters/blockchain-core pull request #24
Opened 2023-08-30 15:06 UTC by WaltervonGabain

## Pull Request

### Description

Consensus implementation

### Related Issue

Fixes #20

### Changes Made

miner.js and mempool.js

### How to Test

Cant until the rest is somewaht there

2023-09-01 16:35 UTC, Agn21 approved these changes

2023-09-02 06:01 UTC, rkokhatskyi requested changes

2023-09-02 06:01 UTC, rkokhatskyi commented on src/mempool.js
> +      throw new Error("Invalid transaction");
Can we combine these 2 if statements into one?

2023-09-02 06:01 UTC, rkokhatskyi commented on src/mempool.js
> +  mempool,
we export `mempool` allowing to use it outside of this file and at the same time we have getMempool method in the class itself. They are completely separate now, if you use `mempool` variable only, you will face some errors in the usage places. We need to restrict that for safety

2023-09-02 06:01 UTC, rkokhatskyi commented on src/miner.js
> +    });
you can use a filter function instead of directly modifying the `txs` array inside a loop, this will also make the code cleaner and more readable


```suggestion
    const mempool = getMempool();
    const filteredTxs = mempool.tx.filter((tx) => {
        return (tx instanceof transaction || tx instanceof coinbase) && tx.isValid();
    });
```

2023-09-02 06:01 UTC, rkokhatskyi commented on src/miner.js
> +const miner = new Miner("your_public_key"); // TODO replace with your public key
Let's move this to .env variables (do not commit any keys, just add logic to read from .env variables)

2023-09-02 06:01 UTC, rkokhatskyi commented on src/miner.js
> +  }
let's use an early return Instead of a for loop, you can use JavaScript's `startsWith` method to check if the hex string starts with the required number of zeros. Suggested changes: 


```suggestion
  checkAgainstTarget(hashString) {
    const hex = hashing.stringToHex(hashString);
    return hex.startsWith("0".repeat(miningTarget));
  }
```

2023-09-02 06:01 UTC, rkokhatskyi commented on src/miner.js
> +const { miningTarget } = require("./CONFIG"); // Replace with actual path
Can we include the actual config as well? It is required for miningTarget

2023-09-02 06:01 UTC, rkokhatskyi commented on src/miner.js
> +        Math.floor(Math.random() * 9999999999999999999999999999)
It is unclear what is this expression about, can we have some variable to fetch a nonce and pass it as a parameter here? 

`const nonce = generateRandomNonce();`

2023-09-02 06:03 UTC, rkokhatskyi commented on src/mempool.js
> +  insert_transaction(tx) {
let's use camelCase naming convention for better readability => `insertTransaction` for method name

2023-09-02 06:03 UTC, rkokhatskyi commented on src/mempool.js
> +    if (!tx.is_valid()) {
can we use isValid method to stick to camelCase naming convention?

2023-09-02 06:05 UTC, rkokhatskyi commented on src/mempool.js
> +  }
```suggestion
insertTransaction(tx) {
  if (!(tx instanceof Transaction) || !tx.isValid()) {
    throw new Error("Invalid transaction");
  }

  this.tx.push(tx);
}
```

2023-09-06 12:56 UTC, rkokhatskyi approved these changes
LGTM! 👍

2023-09-06 12:56 UTC, merged